= This is a playground for using Azure OIDC with Confluent Cloud

Please have a look in the subfolders for examples in multiple programming languages.

CAUTION: Everything contained in this repository is not supported by Confluent.

DISCLAIMER AND WARNING: You use this code at your own risk! Please do not use it for production systems. The author may not be held responsible for any harm caused by this code!

== Preconditions

This project requires the following setup.


=== Setup of Azure

Create an "App registrations" in your EntraID tenant. This resource is the global representation of your Confluent Cloud organization. It is connected to one Enterprise Application per Azure Tenant, each of them represent the identity of your Confluent Cloud organization in that tenant.

Conceptually, you could either use your user identity or another app registration representing your own application to request access to the application registration that represents your Confluent Cloud organization. These are completely separate entities in Entra ID. Make sure you don't mix these up with the entities representing your Confluent Cloud organization!

Therefore, when we talk about the app registration or the enterprise application in the following text, we always refer to the app registration/enterprise application which represents your Confluent Cloud organization.

Update the manifest of the app registration and make sure that the version is set like this:

```yaml
"requestedAccessTokenVersion": 2,
```

==== Optionally: Create App Roles
One way to authorize users for specific resources in Confluent Cloud is to configure App Roles in Azure.
Just add roles to your app registration, for example a role called `OrgAdminRole`, and configure it such that both users/groups and applications may get access to it.

You can check the existence of your configured app roles (e.g. "OrgAdminRole") in the tokens provided by the user application by configuring appropriate rules in your identity pool, see below.

In the `API permissions`, add a new permission with a name of your choice.

The App registration always comes with an "Enterprise Application". You can access this using the overview of the app registration. If you want to use roles, you need to restrict access to the enterprise application to selected users/groups and assign your custom roles to them (you find the settings under `Users and Groups`).

==== Alternatively: Use Security Groups

Instead of using roles you can also check for membership in security groups for authorization in Confluent Cloud.

By default, groups are not contained in the tokens issued by Entra ID. In you app registration, you can enable the `groups` token under `Token configuration` by adding a group claim. Make sure to include at least security groups and use the default setting `Group ID` for all of `ID, Access, SAML`.

==== Grant access to the App Registration

You can use regular user accounts in order to acquire access tokens for the CCloud app registration. Alternatively, you can create for each of your clients an addition app registration which represents that client. For each app registration, Azure automatically creates an enterprise application which represents the client in your Azure tenant. You can configure secrets for the individual app registrations (not for the CCloud app registration!) which allows clients to impersonating them.

As a third options, if you run your client code in Azure, you can enable managed identities for your Azure resources. In this case, you can use the managed identity of the resource to acquire access tokens for the CCloud app registration.

If you use roles, grant access to the them to the respective users, enterprise applications, and/or managed identities and make sure you request the correct scope when getting you access tokens.

If you use security groups, you just add the users, enterprise applications or managed identities to the security group(s) you want to use for authorization in Confluent Cloud.
In this case, you can just request the ".default" scope of your CCloud app registration.

==== How to request an access token

If you use a user, you authenticate to Azure as that user. Then you request an access token for the CCloud app registration using the correct URL (you can look that up in the app registration).

With managed identities, the process is similar. Make sure your code can use the managed identity, then request an access token for the CCloud app registration using the correct URL in your code.

If you want to use app registration for your clients, you can use the secret configured for that app registration in your application to get access to the corresponding identity, then use that identity to request an access token for the CCloud app registration.

=== Setup of Confluent Cloud

==== Add Identity Provider to Workload identities

Configure an Entra ID (formerly called "Azure AD") provider with any name and description.

Set the Issuer URL according to the Microsoft documentation, i.e. `https://login.microsoftonline.com/<YOUR-TENANT-ID>/v2.0`.

Set the JWKS URI correctly following the docs, i.e. `
https://login.microsoftonline.com/organizations/discovery/v2.0/keys`.


==== Identity Pool

Create a new identity pool in the identity provider.
You can use `claims.sub` as value for the identity claim field.

Configure a filter. Here, cou can check the existence of your configured app roles (e.g. "OrgAdminRole") in the tokens provided by the user application by configuring appropriate rules in your identity pool. For example:

```text
claims.aud=='Put your Application (client) ID here' &&
'OrgAdminRole' in claims.roles
```

Assign the `OrganizationAdmin` role to the identity pool.

Alternatively (and potentially being the better option), you can check for security groups, if you have configured the groups claim for app registration's tokens (see above).

A rule for checking access to your identity pool could then look like this:

```text
claims.aud=='Put your Application (client) ID here' &&
'<PUT SID OF THE DESIRED SECURITY GROUP HERE>' in claims.groups
```

== Troubleshooting

Try to request a token manually, using this call:

```console
curl --request POST \
--url 'https://YOUR_DOMAIN/oauth/token' \
--header 'content-type: application/x-www-form-urlencoded' \
--data grant_type=client_credentials \
--data client_id=YOUR_CLIENT_ID \
--data client_secret=YOUR_CLIENT_SECRET \
--data scope=YOUR_SCOPE
```


== License

Copyright Eike Thaden, 2023.

See LICENSE file
