/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ethaden.examples.oidc.azure.app;

//import io.confluent.oidc.azure.example.az;

import org.apache.commons.text.WordUtils;

public class ListEnvironments {
    public static void main(String[] args) {
        System.out.println("Found the following environments");
    }
}
