/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ethaden.examples.oidc.azure.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ListEnvironmentsTest {
    @Test void testGetMessage() {
        // Nothing for now
    }
}
