/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.oidc.azure.example.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":identityprovider"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.confluent.oidc.azure.example.app.ListEnvironments")
}
