/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.oidc.azure.example.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ListEnvironmentsTest {
    @Test void testGetMessage() {
        // Nothing for now
    }
}
