/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ethaden.examples.oidc.azure.identityprovider;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AzureIdentityProvider {
    @Test void testConstructor() {
        // Nothing for now
    }
}
